{
 "title": "Kaytu Describe dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "AccountID",
    "query": "select account_id from sources;"
   },
   { "name": "psql", "label": "Namespace", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Describe Scheduler Running [10m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (changes(kaytu_scheduler_describe_jobs_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Describe Connection Running [6h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (status) (changes(kaytu_scheduler_describe_source_jobs_total{status=\"successful\"}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Describe Resource Running [6h]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (status) (changes(kaytu_scheduler_describe_resource_jobs_total{status=\"successful\"}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM describe_connection_jobs \nwhere\n  $__timeFilter(created_at) AND connection_id like $account_id AND status = 'FAILED'\ngroup by status"
    }
   ]
  },
  {
   "title": "Timedout jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM describe_connection_jobs \nwhere\n  $__timeFilter(created_at) AND connection_id like $account_id AND status = 'TIMEOUT'\ngroup by status"
    }
   ]
  },
  {
   "title": "Failure rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "with failed as (\n  SELECT count(*) as failed_count FROM describe_connection_jobs where $__timeFilter(created_at) AND connection_id like $account_id AND status IN ('TIMEOUT', 'FAILED')\n), total as (\n  SELECT count(*) as total_count FROM describe_connection_jobs where $__timeFilter(created_at) AND connection_id like $account_id AND status IN ('TIMEOUT', 'FAILED', 'SUCCEEDED')\n)\nselect sum(failed_count) / sum(total_count) * 100.0  from (select failed_count, 0 as total_count from failed union select 0 as failed_count, total_count from total) as result"
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Describe scheduler processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_describe_jobs_total[1m]))"
    }
   ]
  },
  {
   "title": "Describe connection triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_describe_source_jobs_total[1m]))"
    }
   ]
  },
  {
   "title": "Describe (connection, resourceType) triggered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_describe_resource_jobs_total[1m]))"
    }
   ]
  },
  {
   "title": "Jobs status",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  status, count(*)\nFROM describe_connection_jobs\nwhere\n  $__timeFilter(created_at) AND account_id like $account_id\ngroup by status\nORDER BY status DESC "
    }
   ]
  },
  {
   "title": "Failures by code",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  error_code, count(*)\nFROM describe_connection_jobs\nwhere\n  $__timeFilter(created_at) AND account_id like $account_id AND status = 'FAILED'\ngroup by error_code \nORDER BY count DESC "
    }
   ]
  },
  {
   "title": "Describe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count of resources described",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_resources_described_total[1m]))"
    }
   ]
  },
  {
   "title": "Kafka resource topic message write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"cloud-resources\", namespace=~\"$psql\"}[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Kafka resource topic lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"cloud-resources\", namespace=~\"$psql\"}) by (topic) "
    }
   ]
  },
  {
   "title": "Count of results delivered (pushed to rabbitMQ)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_results_delivered_total[1m]))"
    }
   ]
  },
  {
   "title": "RabbitMQ describe result message write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  },
  {
   "title": "RabbitMQ describe result lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready" }
   ]
  },
  {
   "title": "Count of results processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_results_processed_total[1m]))"
    }
   ]
  },
  {
   "title": "Count of old resources deleted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_old_resources_deleted_total[1m]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Count of stream failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by (status) (rate(kaytu_scheduler_stream_failure_total[1m]))"
    }
   ]
  },
  {
   "title": "Timed out resource types",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  resource_type, count(*)\nFROM describe_connection_jobs\nwhere \n    $__timeFilter(created_at) AND status = 'TIMEOUT' AND account_id like $account_id\ngroup by resource_type\nORDER BY resource_type DESC "
    }
   ]
  },
  {
   "title": "Failed resource types",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  resource_type, count(*)\nFROM describe_connection_jobs\nwhere\n  $__timeFilter(created_at) AND status = 'FAILED' AND account_id like $account_id\ngroup by resource_type\nORDER BY count DESC "
    }
   ]
  },
  {
   "title": "Failure reason",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  resource_type, account_id, updated_at, error_code, failure_message\nFROM describe_connection_jobs dr\nwhere\n  $__timeFilter(created_at) AND \n  status = 'FAILED' AND\n  account_id like $account_id AND\n  NOT(error_code in ('ThrottlingException', 'AccessDeniedException', 'Throttling', 'TooManyRequestsException', '403', '401', 'InsufficientPrivilegesException'))\nORDER BY resource_type ASC "
    }
   ]
  },
  {
   "title": "AccessDenied",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "rawSql": "SELECT\n  resource_type, account_id, updated_at, failure_message\nFROM describe_connection_jobs dr\nwhere\n  $__timeFilter(created_at) AND \n  status = 'FAILED' AND\n  account_id like $account_id AND \n  error_code IN ('AccessDeniedException', '403', '401', 'InsufficientPrivilegesException')\nORDER BY resource_type ASC "
    }
   ]
  },
  {
   "title": "Rate limits",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "rawSql": "SELECT\n  resource_type, account_id, updated_at, failure_message\nFROM describe_connection_jobs dr\nwhere\n  $__timeFilter(created_at) AND \n  status = 'FAILED' AND\n  account_id like $account_id AND \n  error_code IN ('ThrottlingException', 'TooManyRequestsException', 'Throttling')\nORDER BY resource_type ASC "
    }
   ]
  }
 ]
}