{
 "title": "Kaytu Insights Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "AccountID",
    "query": "select account_id from sources;"
   },
   { "name": "psql", "label": "Namespace", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jobs status",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  status, count(*)\nFROM insight_jobs \nwhere\n  $__timeFilter(created_at) AND account_id like $account_id\ngroup by status\nORDER BY status DESC "
    }
   ]
  },
  {
   "title": "Failed resource types",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  insight_id, count(*)\nFROM insight_jobs \nwhere\n  $__timeFilter(created_at) AND status = 'FAILED' AND account_id like $account_id\ngroup by 1\nORDER BY count DESC "
    }
   ]
  },
  {
   "title": "Failure reason",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  insight_id, account_id, updated_at, failure_message\nFROM insight_jobs \nwhere\n  $__timeFilter(created_at) AND \n  status = 'FAILED' AND\n  account_id like $account_id\nORDER BY insight_id ASC "
    }
   ]
  },
  {
   "title": "Unique failure reason",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT\n  insight_id, failure_message, count(*)\nFROM insight_jobs \nwhere\n  $__timeFilter(created_at) AND \n  status = 'FAILED' AND\n  account_id like $account_id\nGROUP BY 1,2\nORDER BY insight_id ASC "
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka resource topic message write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"cloud-resources\", namespace=~\"$psql\"}[1m])) by (topic)"
    }
   ]
  },
  {
   "title": "Kafka resource topic lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=~\"cloud-resources\", namespace=~\"$psql\"}) by (topic) "
    }
   ]
  },
  {
   "title": "RabbitMQ describe result message write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    { "expr": "rabbitmq_queue_messages" }
   ]
  },
  {
   "title": "RabbitMQ describe result lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready" }
   ]
  }
 ]
}