{
 "title": "Kaytu Company Dashboard",
 "tags": [ "kaytu-cli" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "org_email",
    "label": "Organization",
    "query": "SELECT\n  distinct(statistics -> 'orgEmail')\nFROM \n  usage_v2\nWHERE\n  $__timeFilter(created_at)"
   },
   {
    "name": "optimization_type",
    "label": "Optimization Type",
    "query": "ec2-instance,aws-rds,aws-rds-cluster"
   }
  ]
 },
 "panels": [
  {
   "title": "STS ARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "SELECT\n  '${org_email:raw}' " }
   ]
  },
  {
   "title": "Runs over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  date(created_at), count(*)\nFROM usage_v2 \nWHERE (statistics ->> 'orgEmail') like '%${org_email:raw}'\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Run count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM \n  usage_v2\nWHERE \n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  api_endpoint = '${optimization_type:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  (statistics ->> 'savings')::float > 0 and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Resource count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID'))\nFROM \n  usage_v2\nWHERE \n  api_endpoint = '${optimization_type:raw}' and\n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  (statistics ->> 'savings')::float > 0 and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Resource cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float > 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'savings')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float > 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100 FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      (statistics ->> 'savings')::float as savings,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float > 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Optimization runs",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  statistics ->> 'resourceID' as resource_id,\n  created_at,\n  (statistics ->> 'currentCost')::float as current_cost,\n  (statistics ->> 'savings')::float as savings\nFROM \n  usage_v2\nWHERE \n  api_endpoint = '${optimization_type:raw}' and\n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \norder by 1 desc, 2 desc"
    }
   ]
  },
  {
   "title": "Organization Users",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(request -> 'identification' ->> 'sts_arn') as sts_arn\nFROM \n  usage_v2\nWHERE \n  api_endpoint = '${optimization_type:raw}' and\n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Run count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM \n  usage_v2\nWHERE \n  api_endpoint = '${optimization_type:raw}' and\n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  (statistics ->> 'savings')::float <= 0 and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Resource count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID'))\nFROM \n  usage_v2\nWHERE \n  api_endpoint = '${optimization_type:raw}' and\n  (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  (statistics ->> 'savings')::float <= 0 and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Resource cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float <= 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'savings')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float <= 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100 FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      (statistics ->> 'savings')::float as savings,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      api_endpoint = '${optimization_type:raw}' and\n      (statistics ->> 'orgEmail') like '%${org_email:raw}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (statistics ->> 'savings')::float <= 0 and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  }
 ]
}