{
 "title": "Kaytu CLI",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "exclude_negative", "label": "Exclude Negatives", "query": "true,false" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "EC2 Instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'ec2InstanceCurrentCost')::float) as current_cost,\n  sum((statistics ->> 'ec2InstanceRecommendedCost')::float) as recommended_cost,\n  sum((statistics ->> 'ec2InstanceSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'ec2-instance' AND \n  ((statistics ->> 'ec2InstanceSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "EC2 Instance saving",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'ec2InstanceSavings')::float) / sum((statistics ->> 'ec2InstanceCurrentCost')::float) * 100.0 as saving_percentage\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'ec2-instance' AND \n  ((statistics ->> 'ec2InstanceSavings')::float > 0 or not($exclude_negative) ) and\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "EC2 Instance (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) as current_cost, sum(recommended_cost) as recommended_cost, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'ec2InstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'ec2InstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'ec2InstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'ec2-instance' AND \n      ((statistics ->> 'ec2InstanceSavings')::float > 0 or not($exclude_negative) ) and\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "EC2 Instance savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  sum(savings) / sum(current_cost) * 100.0 FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'ec2InstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'ec2InstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'ec2InstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'ec2-instance' AND \n      ((statistics ->> 'ec2InstanceSavings')::float > 0 or not($exclude_negative) ) and\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "EBS Volume",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'ebsCurrentCost')::float) as current_cost,\n  sum((statistics ->> 'ebsRecommendedCost')::float) as recommended_cost,\n  sum((statistics ->> 'ebsSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'ec2-instance' AND \n  ((statistics ->> 'ebsSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "EBS Volume savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'ebsSavings')::float) / sum((statistics ->> 'ebsCurrentCost')::float) * 100.0 as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'ec2-instance' AND \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n    ((statistics ->> 'ebsSavings')::float > 0 or not($exclude_negative) ) AND\n  $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "EBS Volume (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) as current_cost, sum(recommended_cost) as recommended_cost, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'ebsCurrentCost')::float) as current_cost,\n      ((statistics ->> 'ebsRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'ebsSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'ec2-instance' AND \n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n      ((statistics ->> 'ebsSavings')::float > 0 or not($exclude_negative) ) AND\n       $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "EBS Volume savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100.0 as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'ebsCurrentCost')::float) as current_cost,\n      ((statistics ->> 'ebsRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'ebsSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'ec2-instance' AND \n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n      ((statistics ->> 'ebsSavings')::float > 0 or not($exclude_negative) ) AND\n      $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "RDS Instance",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n  sum((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n  sum((statistics ->> 'rdsInstanceSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds' AND \n  ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "RDS Instance savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'rdsInstanceSavings')::float) / sum((statistics ->> 'rdsInstanceCurrentCost')::float) * 100.0 as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds' AND \n  ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "RDS Instance (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) as current_cost, sum(recommended_cost) as recommended_cost, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'rdsInstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'aws-rds' AND \n      ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "RDS Instance savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100.0 as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'rdsInstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'aws-rds' AND \n      ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "RDS Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n  sum((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n  sum((statistics ->> 'rdsInstanceSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds-cluster' AND \n  ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "RDS Cluster savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'rdsInstanceSavings')::float) / sum((statistics ->> 'rdsInstanceCurrentCost')::float) * 100.0 as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds-cluster' AND \n  ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "RDS Cluster (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) as current_cost, sum(recommended_cost) as recommended_cost, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'rdsInstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'aws-rds-cluster' AND \n      ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "RDS Cluster savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100.0 as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'rdsInstanceCurrentCost')::float) as current_cost,\n      ((statistics ->> 'rdsInstanceRecommendedCost')::float) as recommended_cost,\n      ((statistics ->> 'rdsInstanceSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint = 'aws-rds-cluster' AND \n      ((statistics ->> 'rdsInstanceSavings')::float > 0 or not($exclude_negative) ) AND\n      not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "Kubernetes CPU Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'kubernetesCurrentCPU')::float) as current_cpu,\n  sum((statistics ->> 'kubernetesRecommendedCPU')::float) as recommended_cpu,\n  sum((statistics ->> 'kubernetesCPUSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint like 'kubernetes-%' AND \n  ((statistics ->> 'kubernetesCPUSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes CPU Request savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'kubernetesCPUSavings')::float) / sum((statistics ->> 'kubernetesCurrentCPU')::float) * 100.0 as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint like 'kubernetes-%' AND \n  ((statistics ->> 'kubernetesCPUSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes CPU Request (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cpu) as current_cpu, sum(recommended_cpu) as recommended_cpu, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'kubernetesCurrentCPU')::float) as current_cpu,\n      ((statistics ->> 'kubernetesRecommendedCPU')::float) as recommended_cpu,\n      ((statistics ->> 'kubernetesCPUSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint like 'kubernetes-%' AND \n      ((statistics ->> 'kubernetesCPUSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "Kubernetes CPU Request savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cpu) * 100.0 as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'kubernetesCurrentCPU')::float) as current_cpu,\n      ((statistics ->> 'kubernetesRecommendedCPU')::float) as recommended_cpu,\n      ((statistics ->> 'kubernetesCPUSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint like 'kubernetes-%' AND \n      ((statistics ->> 'kubernetesCPUSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "Kubernetes Memory Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'kubernetesCurrentMemoryRequest')::float) as current_memory,\n  sum((statistics ->> 'kubernetesRecommendedMemoryRequest')::float) as recommended_memory,\n  sum((statistics ->> 'KubernetesMemoryRequestSavings')::float) as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint like 'kubernetes-%' AND \n  ((statistics ->> 'KubernetesMemoryRequestSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes Memory Request savings",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sum((statistics ->> 'KubernetesMemoryRequestSavings')::float) / sum((statistics ->> 'kubernetesCurrentMemoryRequest')::float) * 100.0 as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint like 'kubernetes-%' AND \n  ((statistics ->> 'KubernetesMemoryRequestSavings')::float > 0  or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0)  )AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes Memory Request savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_memory) as current_memory, sum(recommended_memory) as recommended_memory, sum(savings) as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'kubernetesCurrentMemoryRequest')::float) as current_memory,\n      ((statistics ->> 'kubernetesRecommendedMemoryRequest')::float) as recommended_memory,\n      ((statistics ->> 'KubernetesMemoryRequestSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint like 'kubernetes-%' AND \n      ((statistics ->> 'KubernetesMemoryRequestSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "Kubernetes Memory Request savings (Excluding re-runs)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cpu) * 100.0 as savings FROM (\n  SELECT *, max(id) over (partition by resource_id) as max_id FROM (\n    SELECT \n      id,\n      statistics ->> 'resourceID' as resource_id,\n      ((statistics ->> 'kubernetesCurrentMemoryRequest')::float) as current_cpu,\n      ((statistics ->> 'kubernetesRecommendedMemoryRequest')::float) as recommended_cpu,\n      ((statistics ->> 'KubernetesMemoryRequestSavings')::float) as savings\n    FROM \n      usage_v2 \n    WHERE \n      api_endpoint like 'kubernetes-%' AND \n      ((statistics ->> 'KubernetesMemoryRequestSavings')::float > 0 or (not($exclude_negative) and (statistics ->> 'kubernetesCPUSavings')::float != 0) ) AND\n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks'))\n      and $__timeFilter(created_at) \n  ) as t1\n) as t2 where max_id = id"
    }
   ]
  },
  {
   "title": "accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'accountID')) as accountID\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Organizations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'orgEmail')) as organizations\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and\n  not((statistics ->> 'orgEmail') like '%gmail.com%')\n  and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Personal Orgs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'orgEmail')) as organizations\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and\n  ((statistics ->> 'orgEmail') like '%gmail.com%')"
    }
   ]
  },
  {
   "title": "EC2 Instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as ec2_instance\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and \n  api_endpoint = 'ec2-instance' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "EBS Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(c) FROM (\nSELECT\n  distinct(statistics ->> 'resourceID') as resource_id,\n  (statistics ->> 'ebsVolumeCount')::integer as c\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\nand $__timeFilter(created_at) \n) as t"
    }
   ]
  },
  {
   "title": "RDS Instance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as ec2_instance\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  api_endpoint = 'aws-rds' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "RDS Cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as ec2_instance\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  api_endpoint = 'aws-rds-cluster' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM (\nSELECT\n  (statistics ->> 'accountID') as kubernetes_clusters,\n  (statistics ->> 'auth0UserId') as auth0UserId\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint like 'kubernetes-%' and \n  $__timeFilter(created_at) \ngroup by 1,2\n) as t "
    }
   ]
  },
  {
   "title": "Kubernetes Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as kubernetes_pods\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint = 'kubernetes-pod' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes Deployments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as kubernetes_deployments\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint = 'kubernetes-deployment' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes DaemonSets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as kubernetes_daemonset\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint = 'kubernetes-daemonset' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes StatefulSets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as kubernetes_statefulset\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint = 'kubernetes-statefulset' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "Kubernetes Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(statistics ->> 'resourceID')) as kubernetes_jobs\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'kaytu-aks@local.temp', 'clusterUser_kaytu-development_kaytu-aks')) and \n  api_endpoint = 'kubernetes-job' and $__timeFilter(created_at) "
    }
   ]
  },
  {
   "title": "accounts",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  (statistics ->> 'accountID') as accountID,\n  count(*)\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'clusterUser_kaytu-development_kaytu-aks', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and $__timeFilter(created_at) \ngroup by 1"
    }
   ]
  },
  {
   "title": "identities",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 4, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  (request -> 'identification' -> 'sts_arn') as identities,\n  count(*),\n  sum((statistics ->> 'savings')::float) as total_savings\nFROM \n  usage_v2\nWHERE not(statistics ->> 'accountID' in ('', 'clusterUser_kaytu-development_kaytu-aks', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and $__timeFilter(created_at) \ngroup by 1"
    }
   ]
  },
  {
   "title": "personal orgs",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 12, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  (statistics ->> 'orgEmail') as email,\n  count(*),\n  sum((statistics ->> 'savings')::float) as total_savings\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and\n  ((statistics ->> 'orgEmail') like '%gmail.com%') \n  and $__timeFilter(created_at) \ngroup by 1"
    }
   ]
  },
  {
   "title": "organizations",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 59 },
   "targets": [
    {
     "rawSql": "SELECT\n  (statistics ->> 'orgEmail') as email,\n  count(*),\n  sum((statistics ->> 'savings')::float) as total_savings\nFROM \n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', 'clusterUser_kaytu-development_kaytu-aks', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) and\n  not((statistics ->> 'orgEmail') like '%gmail.com%')\n  and $__timeFilter(created_at) \n  group by 1"
    }
   ]
  },
  {
   "title": "Plugin version used",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n  request -> 'cliVersion' as _version,\n  count(*)\nFROM \n  usage_v2 \nWHERE \n  not(statistics ->> 'accountID' in ('', 'clusterUser_kaytu-development_kaytu-aks', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) \nGROUP BY 1\norder by 2 desc"
    }
   ]
  },
  {
   "title": "Github downloads",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 10, "x": 9, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select \n  key as _version, \n  value::int as count \nfrom \n  jsonb_each('{\"0.0.4\":1,\"0.0.5\":1,\"0.0.7\":160,\"0.1.1\":111,\"0.1.2\":1,\"0.2.7\":1,\"0.3.1\":3,\"0.3.10\":1,\"0.3.18\":3,\"0.3.19\":1,\"0.3.20\":1,\"0.3.21\":1,\"0.3.22\":7,\"0.3.23\":7,\"0.3.24\":7,\"0.3.25\":7,\"0.3.26\":7,\"0.3.27\":7,\"0.3.28\":9,\"0.3.29\":11,\"0.3.30\":6,\"0.3.31\":11,\"0.3.32\":9,\"0.3.33\":7,\"0.3.34\":8,\"0.3.35\":7,\"0.3.36\":9,\"0.3.37\":7,\"0.3.38\":7,\"0.3.39\":14,\"0.3.40\":6,\"0.3.41\":7,\"0.3.42\":7,\"0.3.43\":7,\"0.3.44\":7,\"0.3.45\":7,\"0.3.46\":8,\"0.3.47\":13,\"0.3.48\":12,\"0.3.49\":15,\"0.3.50\":29,\"0.3.51\":9,\"0.3.52\":10,\"0.3.53\":10,\"0.3.54\":10,\"0.3.55\":9,\"0.3.56\":9,\"0.3.57\":12,\"0.3.58\":72,\"0.3.59\":9,\"0.3.60\":24,\"0.3.9\":1,\"0.4.0\":7,\"0.4.1\":145,\"0.5.0\":20,\"0.5.1\":48,\"0.5.2\":6,\"0.5.3\":7,\"0.5.4\":22,\"0.5.5\":208,\"0.6.0\":35,\"0.6.1\":55,\"0.6.2\":45,\"0.6.3\":24,\"0.7.0\":8,\"0.7.1\":8,\"0.7.10\":64,\"0.7.10-rc.0\":3,\"0.7.12-rc.0\":1,\"0.7.13-rc.0\":2,\"0.7.3\":6,\"0.7.3-rc.0\":1,\"0.7.4\":37,\"0.7.5\":31,\"0.7.5-rc.0\":1,\"0.7.5-rc.1\":2,\"0.7.7\":24,\"0.7.8\":26,\"0.7.9\":37,\"0.8.0\":13,\"0.8.1\":13,\"0.8.1-rc.0\":1,\"0.8.2\":21,\"0.8.3\":33,\"0.8.4\":10,\"0.8.5\":39,\"0.8.6-rc.0\":1,\"0.8.7-rc.0\":1,\"0.8.8-rc.0\":1,\"0.8.9-rc.0\":2,\"0.9.0-rc.0\":2,\"0.9.1-rc.0\":2,\"0.9.3-rc.0\":2,\"0.9.4-rc.0\":2,\"0.9.5-rc.0\":2}'::jsonb) \norder by 2 desc\nlimit 20"
    }
   ]
  },
  {
   "title": "Total Github downloads",
   "type": "stat",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum(value::int) \nfrom \n  jsonb_each('{\"0.0.4\":1,\"0.0.5\":1,\"0.0.7\":160,\"0.1.1\":111,\"0.1.2\":1,\"0.2.7\":1,\"0.3.1\":3,\"0.3.10\":1,\"0.3.18\":3,\"0.3.19\":1,\"0.3.20\":1,\"0.3.21\":1,\"0.3.22\":7,\"0.3.23\":7,\"0.3.24\":7,\"0.3.25\":7,\"0.3.26\":7,\"0.3.27\":7,\"0.3.28\":9,\"0.3.29\":11,\"0.3.30\":6,\"0.3.31\":11,\"0.3.32\":9,\"0.3.33\":7,\"0.3.34\":8,\"0.3.35\":7,\"0.3.36\":9,\"0.3.37\":7,\"0.3.38\":7,\"0.3.39\":14,\"0.3.40\":6,\"0.3.41\":7,\"0.3.42\":7,\"0.3.43\":7,\"0.3.44\":7,\"0.3.45\":7,\"0.3.46\":8,\"0.3.47\":13,\"0.3.48\":12,\"0.3.49\":15,\"0.3.50\":29,\"0.3.51\":9,\"0.3.52\":10,\"0.3.53\":10,\"0.3.54\":10,\"0.3.55\":9,\"0.3.56\":9,\"0.3.57\":12,\"0.3.58\":72,\"0.3.59\":9,\"0.3.60\":24,\"0.3.9\":1,\"0.4.0\":7,\"0.4.1\":145,\"0.5.0\":20,\"0.5.1\":48,\"0.5.2\":6,\"0.5.3\":7,\"0.5.4\":22,\"0.5.5\":208,\"0.6.0\":35,\"0.6.1\":55,\"0.6.2\":45,\"0.6.3\":24,\"0.7.0\":8,\"0.7.1\":8,\"0.7.10\":64,\"0.7.10-rc.0\":3,\"0.7.12-rc.0\":1,\"0.7.13-rc.0\":2,\"0.7.3\":6,\"0.7.3-rc.0\":1,\"0.7.4\":37,\"0.7.5\":31,\"0.7.5-rc.0\":1,\"0.7.5-rc.1\":2,\"0.7.7\":24,\"0.7.8\":26,\"0.7.9\":37,\"0.8.0\":13,\"0.8.1\":13,\"0.8.1-rc.0\":1,\"0.8.2\":21,\"0.8.3\":33,\"0.8.4\":10,\"0.8.5\":39,\"0.8.6-rc.0\":1,\"0.8.7-rc.0\":1,\"0.8.8-rc.0\":1,\"0.8.9-rc.0\":2,\"0.9.0-rc.0\":2,\"0.9.1-rc.0\":2,\"0.9.3-rc.0\":2,\"0.9.4-rc.0\":2,\"0.9.5-rc.0\":2}'::jsonb) \n"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', created_at) AS time,\n  count(*) AS daily_usage\nFROM\n  usage_v2\nWHERE \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956'))\n  and $__timeFilter(created_at) \nGROUP BY\n  time\nORDER BY\n  time\n"
    }
   ]
  },
  {
   "title": "Negative savings in RDS",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,\n  request -> 'cliVersion' as _version,\n  response -> 'rightSizing' -> 'current' ->> 'instanceType' as currentInstanceType,\n  response -> 'rightSizing' -> 'recommended' ->> 'instanceType' as recommendedInstanceType,\n  (statistics ->> 'savings')::float as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds' AND \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  (statistics ->> 'savings')::float < 0\n  and $__timeFilter(created_at) \nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Negative savings in RDS Cluster",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,\n  request -> 'cliVersion' as _version,\n  response -> 'rightSizing' -> 'current' ->> 'instanceType' as currentInstanceType,\n  response -> 'rightSizing' -> 'recommended' ->> 'instanceType' as recommendedInstanceType,\n  (statistics ->> 'savings')::float as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'aws-rds-cluster' AND \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  (statistics ->> 'savings')::float < 0\n  and $__timeFilter(created_at) \nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Negative savings in EBS",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,\n  request -> 'cliVersion' as _version,\n  value -> 'Current' as currentInstanceType,\n  value -> 'Recommended' as recommendedInstanceType,\n  ((value -> 'Current' -> 'cost')::float - (value -> 'Recommended' -> 'cost')::float) as savings\nFROM \n  usage_v2 cross join jsonb_each(response -> 'volumes')\nWHERE \n  api_endpoint = 'ec2-instance' AND \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  (response ->> 'volumes') != 'null' AND \n  ((value -> 'Current' -> 'cost')::float - (value -> 'Recommended' -> 'cost')::float) < 0\n  and $__timeFilter(created_at) \nORDER BY created_at DESC\n-- SELECT \n--   id,\n--   request -> 'cliVersion' as _version,\n--   v.value -> 'Current' as currentInstanceType,\n--   v.value -> 'Recommended' as recommendedInstanceType,\n--   ((v.value -> 'Current' -> 'cost')::float - (v.value -> 'Recommended' -> 'cost')::float) as savings\n-- FROM \n--   usage_v2 u cross join jsonb_each(response -> 'volumes') as v\n-- WHERE \n--   api_endpoint = 'ec2-instance' AND \n--   not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n--   (SELECT COUNT(*) FROM jsonb_object_keys(response -> 'volumes')) > 0 AND\n--   (value -> 'Current' -> 'cost')::float < 0\n-- ORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Negative savings in EC2",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "rawSql": "SELECT \n  id,\n  request -> 'cliVersion' as _version,\n  response -> 'rightSizing' -> 'current' ->> 'instanceType' as currentInstanceType,\n  response -> 'rightSizing' -> 'recommended' ->> 'instanceType' as recommendedInstanceType,\n  (statistics ->> 'savings')::float as savings\nFROM \n  usage_v2 \nWHERE \n  api_endpoint = 'ec2-instance' AND \n  not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n  (statistics ->> 'savings')::float < 0\n  and $__timeFilter(created_at) \nORDER BY created_at DESC"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "rawSql": "SELECT \n  failure_message, count(*)\nFROM \n  usage_v2\nWHERE \n  not(failure_message is null)\n  and $__timeFilter(created_at) \ngroup by 1\norder by 2 desc\n-- SELECT \n--   id,\n--   request -> 'cliVersion' as _version,\n--   v.value -> 'Current' as currentInstanceType,\n--   v.value -> 'Recommended' as recommendedInstanceType,\n--   ((v.value -> 'Current' -> 'cost')::float - (v.value -> 'Recommended' -> 'cost')::float) as savings\n-- FROM \n--   usage_v2 u cross join jsonb_each(response -> 'volumes') as v\n-- WHERE \n--   api_endpoint = 'ec2-instance' AND \n--   not(statistics ->> 'accountID' in ('', '435670955331', '169193410068', '495355942008', '193049167917', '517592840862', '955636408574', '963827789956')) AND\n--   (SELECT COUNT(*) FROM jsonb_object_keys(response -> 'volumes')) > 0 AND\n--   (value -> 'Current' -> 'cost')::float < 0\n-- ORDER BY created_at DESC"
    }
   ]
  }
 ]
}