{
 "title": "Kaytu Overtime Usage Dashboard",
 "tags": [ "kaytu-cli" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sts_arn",
    "label": "Identity",
    "query": "SELECT\n  distinct(request -> 'identification' -> 'sts_arn')\nFROM \n  usage_v2\n"
   }
  ]
 },
 "panels": [
  {
   "title": "STS ARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "SELECT\n  '${sts_arn:raw}' " }
   ]
  },
  {
   "title": "EC2 Instance Optimization runs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT resource_id, region, account_id, first_executed, first_cost, first_instance_type, last_executed, last_cost, last_saving, last_instance_type FROM (\n  SELECT\n    account_id,\n    region,\n    resource_id,\n    first_value(executed_at) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_executed,\n    first_value(current_cost) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_cost,\n    first_value(savings) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_saving,\n    first_value(instance_type) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_instance_type,\n    first_value(executed_at) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_executed,\n    first_value(current_cost) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_cost,\n    first_value(savings) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_saving,\n    first_value(instance_type) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_instance_type\n  FROM\n  (\n    SELECT\n      statistics ->> 'accountID' as account_id,\n      request ->> 'region' as region,\n      statistics ->> 'resourceID' as resource_id,\n      request -> 'instance' ->> 'instanceType' as instance_type,\n      created_at as executed_at,\n      (statistics ->> 'ec2InstanceCurrentCost')::float as current_cost,\n      (statistics ->> 'ec2InstanceSavings')::float as savings\n    FROM\n      usage_v2\n    WHERE\n      api_endpoint = 'ec2-instance' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (request -> 'identification' ->> 'sts_arn') = '${sts_arn:raw}' and\n      (statistics ->> 'ec2InstanceSavings')::float > 0\n  ) as u\n  order by executed_at desc\n) as u2"
    }
   ]
  },
  {
   "title": "RDS Instance Optimization runs",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT resource_id, region, account_id, first_executed, first_cost,first_instance_type, last_executed, last_cost, last_saving, last_instance_type FROM (\n  SELECT\n    account_id,\n    region,\n    resource_id,\n    first_value(executed_at) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_executed,\n    first_value(current_cost) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_cost,\n    first_value(savings) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_saving,\n    first_value(instance_type) OVER (PARTITION BY resource_id ORDER BY executed_at ASC) as first_instance_type,\n    first_value(executed_at) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_executed,\n    first_value(current_cost) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_cost,\n    first_value(savings) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_saving,\n    first_value(instance_type) OVER (PARTITION BY resource_id ORDER BY executed_at DESC) as last_instance_type\n  FROM\n  (\n    SELECT\n      statistics ->> 'accountID' as account_id,\n      request ->> 'region' as region,\n      statistics ->> 'resourceID' as resource_id,\n      request -> 'instance' ->> 'instanceType' as instance_type,\n      created_at as executed_at,\n      (statistics ->> 'rdsInstanceCurrentCost')::float as current_cost,\n      (statistics ->> 'rdsInstanceSavings')::float as savings\n    FROM\n      usage_v2\n    WHERE\n      api_endpoint = 'aws-rds' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      (request -> 'identification' ->> 'sts_arn') = '${sts_arn:raw}' and\n      (statistics ->> 'rdsInstanceSavings')::float > 0\n  ) as u\n  order by executed_at desc\n) as u2"
    }
   ]
  }
 ]
}