{
 "title": "Kaytu Resource Dashboard",
 "tags": [ "kaytu-cli" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource_id",
    "label": "Resource ID",
    "query": "776b66696e73797373716c2d707264e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
   }
  ]
 },
 "panels": [
  {
   "title": "AccountID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(statistics ->> 'accountID') as account\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Organization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(statistics ->> 'orgEmail') as account\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Run count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*)\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Resource cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      statistics ->> 'resourceID' = '${resource_id}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(current_cost) FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'savings')::float as current_cost,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      statistics ->> 'resourceID' = '${resource_id}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Savings (%)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(savings) / sum(current_cost) * 100 FROM (\n  SELECT *, max(created_at) over (partition by resource_id) as max_created_at FROM (\n    SELECT\n      statistics ->> 'resourceID' as resource_id,\n      (statistics ->> 'currentCost')::float as current_cost,\n      (statistics ->> 'savings')::float as savings,\n      created_at\n    FROM \n      usage_v2\n    WHERE \n      statistics ->> 'resourceID' = '${resource_id}' and\n      ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n      $__timeFilter(created_at) \n  ) as t \n) as j\nWHERE max_created_at = created_at"
    }
   ]
  },
  {
   "title": "Identities who ran this",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(request -> 'identification' ->> 'sts_arn') as sts_arn\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  },
  {
   "title": "Optimization runs",
   "type": "table",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at,\n  (statistics ->> 'currentCost')::float as current_cost,\n  (statistics ->> 'savings')::float as savings\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \norder by 1 desc, 2 desc"
    }
   ]
  },
  {
   "title": "Auto0 Users who ran this",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(statistics ->> 'auth0UserId') as auth0User\nFROM \n  usage_v2\nWHERE \n  statistics ->> 'resourceID' = '${resource_id}' and\n  ((request ->> 'loading') is null or (request ->> 'loading') != 'true') and\n  $__timeFilter(created_at) \n"
    }
   ]
  }
 ]
}