{
 "title": "Kaytu",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Describe Job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (status) (kaytu_describe_worker_do_describe_jobs_total)"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Describe Scheduler running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_describe_jobs_total[1m])"
    }
   ]
  },
  {
   "title": "Describe source job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_describe_source_jobs_total[1m])"
    }
   ]
  },
  {
   "title": "Compliance Scheduler running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_compliance_job_total[5m])"
    }
   ]
  },
  {
   "title": "Compliance source job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_compliance_source_job_total[1m])"
    }
   ]
  },
  {
   "title": "Describe Clean-up Scheduler running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_describe_cleanup_jobs_total[5m])"
    }
   ]
  },
  {
   "title": "Describe clean-up source job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "rate(kaytu_scheduler_schedule_describe_cleanup_source_jobs_total[1m])"
    }
   ]
  }
 ]
}