{
 "title": "NATS Clusters",
 "description": "Jetstream and NATS clusters",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Cluster", "query": { "query": "label_values(job)" } },
   {
    "name": "stream",
    "label": "Stream",
    "query": {
     "query": "label_values(nats_stream_last_seq{job=\"$job\"},stream_name)"
    }
   },
   {
    "name": "consumer",
    "label": "Consumer",
    "query": {
     "query": "label_values(nats_consumer_num_pending{job=\"$job\"},consumer_name)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nats_consumer_num_pending{job=\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Nats - Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_storage{job=\"$job\"})/sum(nats_varz_jetstream_config_max_storage{job=\"$job\"})",
     "legendFormat": "{{clusteri_id}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_jetstream_stats_memory{job=\"$job\"})/sum(nats_varz_jetstream_config_max_memory{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_connections{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Connections per Pod",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_varz_connections{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_varz_slow_consumers{job=\"$job\"}) "
    }
   ]
  },
  {
   "title": "Slow Consumers per Pod",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_varz_slow_consumers{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nats_server_total_consumers{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "NATS Bytes In/Out Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(nats_varz_in_bytes{job=\"$job\"}[5m])",
     "legendFormat": "in - {{ pod }}"
    },
    {
     "expr": "rate(nats_varz_out_bytes{job=\"$job\"}[5m])",
     "legendFormat": "out - {{pod}}"
    }
   ]
  },
  {
   "title": "NATS Msgs In/Out Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_varz_in_msgs{job=\"$job\"}[5m])",
     "legendFormat": "in - {{ pod }}"
    },
    {
     "expr": "rate(nats_varz_out_msgs{job=\"$job\"}[5m])",
     "legendFormat": "out - {{ pod }}"
    }
   ]
  },
  {
   "title": "Jetstream Disks Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cloud:disk_io_throughput:bytes{persistentvolumeclaim=~\"$job.*\"}",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Stream Distribution over servers",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nats_server_total_streams{job=~\"$job\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Jetstream Used Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nats_varz_jetstream_stats_storage{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "NATS Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "nats_varz_total_connections{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Streams & Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": " $stream - Stream data size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_bytes{stream_name=~\"$stream\", job=\"$job\"}) by (stream_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " $stream - Stream message count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_stream_total_messages{stream_name=~\"$stream\", job=\"$job\"}) by (stream_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$stream - Message Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(nats_stream_total_messages{stream_name=~\"$stream\", job=\"$job\"}[5m])) by (stream_name)",
     "legendFormat": "{{stream_name}}"
    }
   ]
  },
  {
   "title": "$stream - Delivered Messages for  Consumers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(rate(nats_consumer_delivered_consumer_seq{stream_name=~\"$stream\", job=\"$job\"}[5m])) by (stream_name,consumer_name)",
     "legendFormat": "{{stream_name}} - {{consumer_name}}"
    }
   ]
  },
  {
   "title": "$stream - Stream Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_stream_last_seq{stream_name=~\"$stream\", job=\"$job\"}[5m])",
     "legendFormat": "{{ stream_name }} : {{ stream_leader }} : {{ pod }}"
    }
   ]
  },
  {
   "title": "$stream - Consumer Re-Delivery [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nats_consumer_num_redelivered{stream_name=~\"$stream\", job=\"$job\"}[5m]) > 0",
     "legendFormat": "{{ stream_name }} - {{ consumer_name }}"
    }
   ]
  },
  {
   "title": "$stream - Consumer Pending Ack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nats_consumer_num_ack_pending{stream_name=~\"$stream\",consumer_name=~\"$consumer\",job=\"$job\"}) by (stream_name,consumer_name)",
     "legendFormat": "{{ stream_name }} - {{ consumer_name }}"
    }
   ]
  },
  { "title": "Cluster Workload Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "$job Pod Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_info{pod=~\"$pod\", container=\"nats\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "$job Pod Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "irate(kube_pod_container_status_restarts_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }} - {{ container }}"
    }
   ]
  },
  {
   "title": "Memory Usage (percent)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{pod=\"$pod\"} / container_spec_memory_limit_bytes{pod=\"$pod\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (percent)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{container!=\"POD\", pod=~\"$pod\"}[5m])) by (pod)/sum(container_spec_cpu_quota{container!=\"POD\", pod=~\"$pod\"} / 1000000) by (pod)) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{pod}} "
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "pod:container_cpu_usage:sum{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "container_spec_cpu_quota{pod=~\"$pod\", container=\"nats\"} /1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "receive {{ pod }}"
    },
    {
     "expr": "-rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])",
     "legendFormat": "transmit {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttling [2m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(container_cpu_cfs_throttled_periods_total{pod=~\"$pod\", container=\"nats\"}[2m]) / increase(container_cpu_cfs_periods_total{pod=~\"$pod\", container=\"nats\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}