{
 "title": "Kaytu Demo Dashboard",
 "time": { "from": "now-4d", "to": "now-2d" },
 "templating": {
  "list": [
   { "name": "connector", "label": "Connector", "query": "AWS,Azure" },
   {
    "name": "timeMillisFrom",
    "query": "select $__unixEpochNanoFrom() / 1000000"
   },
   {
    "name": "timeMillisTo",
    "query": "select $__unixEpochNanoTo() / 1000000"
   }
  ]
 },
 "panels": [
  {
   "title": "No of AWS Accounts",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from kaytu_connections where connector = 'AWS' and lifecycle_state = 'onboard'"
    }
   ]
  },
  {
   "title": "Distribution of platforms on EC2 Instances",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select description -> 'Instance' -> 'PlatformDetails' as platform, count(*) from kaytu_resources where resource_type = 'aws::ec2::instance' group by 1;"
    }
   ]
  },
  {
   "title": "No of Azure Subscriptions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from kaytu_connections where connector = 'Azure' and lifecycle_state = 'onboard'"
    }
   ]
  },
  {
   "title": "No of unhealthy connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from kaytu_connections where health_state = 'unhealthy';"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 20, "x": 4, "y": 11 },
   "targets": [
    {
     "rawSql": "select concat('Spend over ', $__timeFrom()::date, ' - ', $__timeTo()::date)"
    }
   ]
  },
  {
   "title": "Count of EC2 Instances",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from kaytu_lookup where resource_type = 'aws::ec2::instance'"
    }
   ]
  },
  {
   "title": "Top 5 connections by spend on  $connector",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 13 },
   "targets": [
    {
     "rawSql": "select \n  connection_name, \n  sum(cost_value) \nfrom \n  kaytu_cost \nwhere \n  ((connector = $connector) or ($connector = 'all')) and \n  date_epoch >= $timeMillisFrom and \n  date_epoch <= $timeMillisTo and \n  not(cost_value is null) \ngroup by 1 \norder by 2 desc \nlimit 5;"
    }
   ]
  },
  {
   "title": "Top 5 metrics by spend on $connector",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 13 },
   "targets": [
    {
     "rawSql": "select \n  metric_name, \n  sum(cost_value) \nfrom \n  kaytu_cost \nwhere \n  ((connector = $connector) or ($connector = 'all')) and \n  date_epoch >= $timeMillisFrom and \n  date_epoch <= $timeMillisTo and \n  not(cost_value is null) \ngroup by 1 \norder by 2 desc \nlimit 5;"
    }
   ]
  },
  {
   "title": "Count of Compute Virtual Machines",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from kaytu_lookup where resource_type = 'microsoft.compute/virtualmachines'"
    }
   ]
  }
 ]
}